# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 358722efeb032c0d67b541f261fd3df06fd660338b36c621cd5bf6a7ccb9cd4a593bac8431c054f46e1659505375ecbdcaa1cdaad4224aec8c1fc88a01a6f813

test:
  secret_key_base: df2cc7a395351e96bc414bf0d0e0aa6a468fc62ff0214d085f14bd457b19f0755ae96eaf87f43b2e97e63c581e66f98d9c62e55d733c188dce294baf89a0cbb1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
